### ISSUE TITLE
Diseño de la Interfaz de Usuario v1.0

### ISSUE THREAD

**Issue by Luis-Caxi-Calani** [XNICAL/CcontaPub-Doc#1]
Crear mockups y prototipos de la interfaz de usuario de la aplicación.

Criterios de aceptación:
- Se crean mockups para las pantallas principales (inicio de sesión, registro, 
  feed de publicaciones).

**Comment by josue-vy** [comment]
Se hará el prototipo en figma:
se deja el link para ver el progreso
https://www.figma.com/design/dVBsnnxwBQx1VttCwhx8Pa/CconcaPub?t=GFbH8Xx46QA5OqtD-0
